export interface StateLandlordData {
  name: string
  abbr: string
  depositLimit: string
  depositReturn: string
  entryNotice: string
  evictionTimeline: string
  rentControl: string
  landlordFriendly: 'high' | 'medium' | 'low'
  keyFacts: string[]
}

export const STATES: StateLandlordData[] = [
  { name: 'Alabama', abbr: 'AL', depositLimit: 'No limit', depositReturn: '60 days', entryNotice: '2 days', evictionTimeline: '4–8 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No mandatory habitability statute — common law applies', 'Pay or quit notice: 7 days', 'No rent control statewide'] },
  { name: 'Alaska', abbr: 'AK', depositLimit: '2 months rent', depositReturn: '14 days (no deductions) / 30 days (with deductions)', entryNotice: '24 hours', evictionTimeline: '4–8 weeks', rentControl: 'None', landlordFriendly: 'medium', keyFacts: ['Security deposit earns interest if held >6 months', 'Pay or quit: 7 days', 'No rent control statewide'] },
  { name: 'Arizona', abbr: 'AZ', depositLimit: '1.5 months rent', depositReturn: '14 days', entryNotice: '48 hours', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted statewide)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control — no city can enact it', 'Pay or quit: 5 days', 'Written lease required for tenancies over 1 year'] },
  { name: 'Arkansas', abbr: 'AR', depositLimit: '2 months rent', depositReturn: '60 days', entryNotice: 'Not specified', evictionTimeline: '3–6 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No implied warranty of habitability by statute', 'Pay or quit: 3 days', 'One of the most landlord-favorable states in the country'] },
  { name: 'California', abbr: 'CA', depositLimit: '1 month rent (unfurnished)', depositReturn: '21 days', entryNotice: '24 hours', evictionTimeline: '3–6 months', rentControl: 'Statewide AB 1482 + local ordinances', landlordFriendly: 'low', keyFacts: ['AB 1482 caps annual rent increases at 5% + CPI for covered units', 'Just cause eviction required after 12 months', 'Some cities (LA, SF, Oakland) have stricter local rent control'] },
  { name: 'Colorado', abbr: 'CO', depositLimit: 'No limit', depositReturn: '30 days (1 month for SFR)', entryNotice: '24 hours', evictionTimeline: '4–7 weeks', rentControl: 'Limited local authority', landlordFriendly: 'medium', keyFacts: ['Denver and some cities may enact rent stabilization', 'Pay or quit: 10 days', 'Landlord must provide working heating/cooling as of 2021 law'] },
  { name: 'Connecticut', abbr: 'CT', depositLimit: '2 months rent (1 month for 62+)', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '6–12 weeks', rentControl: 'Local option', landlordFriendly: 'low', keyFacts: ['Strong tenant protections', 'Pay or quit: 3 days', 'Some towns have rent control ordinances'] },
  { name: 'Delaware', abbr: 'DE', depositLimit: '1 month rent (after 1 year)', depositReturn: '20 days', entryNotice: '2 days', evictionTimeline: '5–10 weeks', rentControl: 'None', landlordFriendly: 'medium', keyFacts: ['Pay or quit: 5 days', 'Landlord must provide move-in checklist', 'No statewide rent control'] },
  { name: 'Florida', abbr: 'FL', depositLimit: 'No limit', depositReturn: '15 days (no deductions) / 30 days (with deductions)', entryNotice: '12 hours', evictionTimeline: '4–6 weeks', rentControl: 'Preempted statewide (2023)', landlordFriendly: 'high', keyFacts: ['2023 law preempts all local rent control — none allowed', 'Pay or quit: 3 days', 'Landlord must maintain roof, exterior walls, and structural components'] },
  { name: 'Georgia', abbr: 'GA', depositLimit: 'No limit', depositReturn: '30 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: notice to pay immediately', 'Dispossessory process is streamlined and fast'] },
  { name: 'Hawaii', abbr: 'HI', depositLimit: '1 month rent', depositReturn: '14 days', entryNotice: '2 days', evictionTimeline: '5–10 weeks', rentControl: 'Local option', landlordFriendly: 'low', keyFacts: ['Honolulu has considered rent control measures', 'Pay or quit: 5 days', 'Extremely tight rental market statewide'] },
  { name: 'Idaho', abbr: 'ID', depositLimit: 'No limit', depositReturn: '21 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Minimal landlord regulation'] },
  { name: 'Illinois', abbr: 'IL', depositLimit: 'No limit (Chicago: 1.5 months)', depositReturn: '30 days', entryNotice: '2 days', evictionTimeline: '5–12 weeks', rentControl: 'Chicago and some suburbs', landlordFriendly: 'medium', keyFacts: ['Chicago Residential Landlord and Tenant Ordinance is comprehensive', 'Chicago requires interest on security deposits', 'Cook County has additional tenant protections'] },
  { name: 'Indiana', abbr: 'IN', depositLimit: 'No limit', depositReturn: '45 days', entryNotice: 'Reasonable notice', evictionTimeline: '4–7 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 10 days', 'Simple eviction process'] },
  { name: 'Iowa', abbr: 'IA', depositLimit: '2 months rent', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '4–7 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Landlord-tenant act closely follows URLTA'] },
  { name: 'Kansas', abbr: 'KS', depositLimit: '1 month rent (unfurnished) / 1.5 months (furnished)', depositReturn: '14–30 days', entryNotice: 'Reasonable notice', evictionTimeline: '3–6 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No rent control statewide', 'Pay or quit: 3 days', 'Deposit held in separate account required'] },
  { name: 'Kentucky', abbr: 'KY', depositLimit: 'No limit', depositReturn: '30–60 days', entryNotice: '2 days', evictionTimeline: '4–8 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['URLTA applies in some counties only', 'Pay or quit: 7 days', 'Landlord-friendly legal environment'] },
  { name: 'Louisiana', abbr: 'LA', depositLimit: 'No limit', depositReturn: '1 month', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', '5-day notice to vacate for nonpayment', 'Rule for possession is a distinct legal concept under Louisiana civil law'] },
  { name: 'Maine', abbr: 'ME', depositLimit: '2 months rent', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '5–8 weeks', rentControl: 'Local option', landlordFriendly: 'medium', keyFacts: ['Portland has rent control ordinance', 'Pay or quit: 7 days', 'Landlord must provide written receipt for security deposit'] },
  { name: 'Maryland', abbr: 'MD', depositLimit: '2 months rent', depositReturn: '45 days', entryNotice: 'Not specified', evictionTimeline: '5–8 weeks', rentControl: 'Montgomery County and others', landlordFriendly: 'medium', keyFacts: ['Montgomery and Prince George\'s counties have local tenant protections', 'Pay or quit: 4 days', 'Failure to return deposit within 45 days = landlord forfeits right to retain'] },
  { name: 'Massachusetts', abbr: 'MA', depositLimit: '1 month rent', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '6–10 weeks', rentControl: 'Boston studying', landlordFriendly: 'low', keyFacts: ['One of the strictest landlord-tenant frameworks in the US', 'Last month\'s rent AND security deposit = 2 months max total', 'Cambridge had rent control until 1994 statewide ban; pressure to reinstate'] },
  { name: 'Michigan', abbr: 'MI', depositLimit: '1.5 months rent', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '4–8 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 7 days', 'Landlord must provide itemized deposit accounting'] },
  { name: 'Minnesota', abbr: 'MN', depositLimit: 'No limit', depositReturn: '21 days', entryNotice: 'Reasonable notice', evictionTimeline: '4–8 weeks', rentControl: 'Minneapolis and St. Paul', landlordFriendly: 'medium', keyFacts: ['Minneapolis and St. Paul have rent stabilization ordinances (3% cap)', 'Pay or quit: varies', 'Minnesota has an implied covenants of habitability by statute'] },
  { name: 'Mississippi', abbr: 'MS', depositLimit: 'No limit', depositReturn: '45 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Minimal landlord regulation'] },
  { name: 'Missouri', abbr: 'MO', depositLimit: '2 months rent', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '4–7 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: immediate notice in some cases', 'St. Louis has some additional local tenant protections'] },
  { name: 'Montana', abbr: 'MT', depositLimit: 'No limit', depositReturn: '10–30 days', entryNotice: '24 hours', evictionTimeline: '4–7 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Return deadline depends on reason for withholding'] },
  { name: 'Nebraska', abbr: 'NE', depositLimit: '1 month rent', depositReturn: '14 days', entryNotice: '1 day', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 7 days', 'One of the shorter deposit return windows in the US'] },
  { name: 'Nevada', abbr: 'NV', depositLimit: '3 months rent', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 7 days', 'Las Vegas and Reno are predominantly landlord-friendly courts'] },
  { name: 'New Hampshire', abbr: 'NH', depositLimit: '1 month rent or $100 (whichever is greater)', depositReturn: '30 days', entryNotice: 'Adequate notice', evictionTimeline: '5–8 weeks', rentControl: 'None', landlordFriendly: 'medium', keyFacts: ['No statewide rent control', 'Eviction notice: 7 or 30 days depending on violation', 'Deposit must be held in escrow account'] },
  { name: 'New Jersey', abbr: 'NJ', depositLimit: '1.5 months rent', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '2–4 months', rentControl: 'Many municipalities', landlordFriendly: 'low', keyFacts: ['Anti-Eviction Act requires just cause in most situations', 'Dozens of NJ municipalities have rent control', 'Landlord must pay interest on security deposit annually'] },
  { name: 'New Mexico', abbr: 'NM', depositLimit: '1 month rent', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '4–8 weeks', rentControl: 'None (Santa Fe studied)', landlordFriendly: 'medium', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Owner of 4+ units must keep deposit in separate account'] },
  { name: 'New York', abbr: 'NY', depositLimit: '1 month rent', depositReturn: '14 days', entryNotice: 'Reasonable notice', evictionTimeline: '3–6 months', rentControl: 'NYC rent stabilization + some municipalities', landlordFriendly: 'low', keyFacts: ['Housing Stability and Tenant Protection Act (2019) significantly strengthened tenant rights', 'NYC has ~1 million rent-stabilized units', 'Security deposit law strictly enforced — missing 14-day deadline is very costly'] },
  { name: 'North Carolina', abbr: 'NC', depositLimit: '2 months (month-to-month) / 1.5 months (over 2 months)', depositReturn: '30 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 10 days', 'Summary ejectment process is landlord-friendly'] },
  { name: 'North Dakota', abbr: 'ND', depositLimit: '1 month rent (unfurnished)', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Minimal landlord regulation'] },
  { name: 'Ohio', abbr: 'OH', depositLimit: 'No limit', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '5–8 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 3 days', 'Must pay interest on deposits over $50 held over 6 months'] },
  { name: 'Oklahoma', abbr: 'OK', depositLimit: 'No limit', depositReturn: '30–45 days', entryNotice: '1 day', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 5 days', 'Minimal tenant protections by statute'] },
  { name: 'Oregon', abbr: 'OR', depositLimit: 'No limit', depositReturn: '31 days', entryNotice: '24 hours', evictionTimeline: '4–8 weeks', rentControl: 'Statewide (7% + CPI cap)', landlordFriendly: 'low', keyFacts: ['First state to enact statewide rent control (2019)', 'Just cause eviction required after 12 months', 'Portland has additional local tenant protections'] },
  { name: 'Pennsylvania', abbr: 'PA', depositLimit: '2 months (first year) / 1 month (after)', depositReturn: '30 days', entryNotice: 'Reasonable notice', evictionTimeline: '4–8 weeks', rentControl: 'None (preempted)', landlordFriendly: 'medium', keyFacts: ['State preempts local rent control', 'Pay or quit: 10 days', 'Must pay interest on deposits held over 2 years'] },
  { name: 'Rhode Island', abbr: 'RI', depositLimit: '1 month rent', depositReturn: '20 days', entryNotice: '2 days', evictionTimeline: '5–8 weeks', rentControl: 'Providence studying', landlordFriendly: 'medium', keyFacts: ['No statewide rent control currently', 'Pay or quit: 5 days', 'Tenant can terminate for landlord failure to repair'] },
  { name: 'South Carolina', abbr: 'SC', depositLimit: 'No limit', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 5 days', 'Simple, landlord-favorable eviction process'] },
  { name: 'South Dakota', abbr: 'SD', depositLimit: '1 month rent', depositReturn: '14 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'One of the shorter deposit return windows'] },
  { name: 'Tennessee', abbr: 'TN', depositLimit: 'No limit', depositReturn: 'End of tenancy', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 14 days', 'Nashville real estate market is strong for landlords'] },
  { name: 'Texas', abbr: 'TX', depositLimit: 'No limit', depositReturn: '30 days', entryNotice: 'Not specified', evictionTimeline: '3–4 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['Fastest eviction state in the US', 'State preempts local rent control — cities cannot enact it', 'Pay or quit: 3 days'] },
  { name: 'Utah', abbr: 'UT', depositLimit: 'No limit', depositReturn: '30 days', entryNotice: '24 hours', evictionTimeline: '3–5 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 3 days', 'Salt Lake City has very tight vacancy rates'] },
  { name: 'Vermont', abbr: 'VT', depositLimit: 'No limit', depositReturn: '14 days', entryNotice: '48 hours', evictionTimeline: '6–10 weeks', rentControl: 'None', landlordFriendly: 'medium', keyFacts: ['No statewide rent control', 'Pay or quit: 14 days', 'Strong habitability requirements'] },
  { name: 'Virginia', abbr: 'VA', depositLimit: '2 months rent', depositReturn: '45 days', entryNotice: '24 hours', evictionTimeline: '4–7 weeks', rentControl: 'Local option (Northern VA)', landlordFriendly: 'medium', keyFacts: ['Northern Virginia localities can adopt rent control', 'Pay or quit: 5 days', 'Landlord must provide written receipts for cash deposits'] },
  { name: 'Washington', abbr: 'WA', depositLimit: 'No limit', depositReturn: '21 days', entryNotice: '2 days', evictionTimeline: '4–8 weeks', rentControl: 'Seattle and some cities', landlordFriendly: 'low', keyFacts: ['Seattle has just cause eviction ordinance', 'New state law restricts move-in fees', 'Pay or quit: 14 days'] },
  { name: 'West Virginia', abbr: 'WV', depositLimit: 'No limit', depositReturn: '60–65 days', entryNotice: 'Reasonable notice', evictionTimeline: '4–7 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: notice to pay immediately', 'Minimal tenant protection statutes'] },
  { name: 'Wisconsin', abbr: 'WI', depositLimit: 'No limit', depositReturn: '21 days', entryNotice: '12 hours', evictionTimeline: '4–7 weeks', rentControl: 'None (preempted)', landlordFriendly: 'high', keyFacts: ['State preempts local rent control', 'Pay or quit: 5 days', 'Notice to enter: 12 hours is one of the shorter requirements'] },
  { name: 'Wyoming', abbr: 'WY', depositLimit: 'No limit', depositReturn: '30–60 days', entryNotice: 'Not specified', evictionTimeline: '3–5 weeks', rentControl: 'None', landlordFriendly: 'high', keyFacts: ['No statewide rent control', 'Pay or quit: 3 days', 'Minimal landlord regulation statewide'] },
  { name: 'Washington DC', abbr: 'DC', depositLimit: '1 month rent', depositReturn: '45 days', entryNotice: 'Reasonable notice', evictionTimeline: '2–4 months', rentControl: 'Yes (DC Rent Control)', landlordFriendly: 'low', keyFacts: ['Among the strongest tenant protections in the US', 'Most units built before 1978 are rent controlled', 'Just cause eviction required'] },
]

export function getStateData(abbr: string): StateLandlordData | undefined {
  return STATES.find(s => s.abbr.toLowerCase() === abbr.toLowerCase() || s.name.toLowerCase() === abbr.toLowerCase())
}

export function getStatePath(state: StateLandlordData): string {
  return state.abbr.toLowerCase()
}
