// Comprehensive 50-state + DC landlord law data
export interface StateLawData {
  code: string;
  name: string;
  landlordScore: number; // 1-10 (10 = most landlord-friendly)
  evictionNoticeDays: number;
  evictionTotalDays: number;
  securityDepositMax: string;
  rentControl: boolean;
  rentControlCities: string[];
  lateFeeCap: string;
  entryNoticeHours: number;
  requiredDisclosures: string[];
  keyTenantRights: string[];
  keyLandlordRights: string[];
  localCourts: { name: string; url: string }[];
  evictionFilingFee: string;
  winterEvictionBan: boolean;
}

export const scoreToColor = (score: number): string => {
  if (score >= 8) return '#22C55E';
  if (score >= 6) return '#84CC16';
  if (score >= 5) return '#D4A843';
  if (score >= 3) return '#F97316';
  return '#EF4444';
};

export const scoreToLabel = (score: number): string => {
  if (score >= 8) return 'Landlord Friendly';
  if (score >= 6) return 'Balanced';
  if (score >= 5) return 'Neutral';
  if (score >= 3) return 'Tenant Leaning';
  return 'Tenant Friendly';
};

export const STATE_LAWS: StateLawData[] = [
  { code: 'AL', name: 'Alabama', landlordScore: 8, evictionNoticeDays: 7, evictionTotalDays: 30, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 2, requiredDisclosures: ['Lead paint (pre-1978)', 'Move-in checklist'], keyTenantRights: ['Habitable conditions', 'Privacy rights'], keyLandlordRights: ['Quick eviction process', 'No rent control', 'No late fee cap'], localCourts: [{ name: 'Alabama Courts', url: 'https://alacourt.gov' }], evictionFilingFee: '$156–$200', winterEvictionBan: false },
  { code: 'AK', name: 'Alaska', landlordScore: 6, evictionNoticeDays: 7, evictionTotalDays: 45, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Landlord identity'], keyTenantRights: ['24-hr entry notice', 'Repair & deduct'], keyLandlordRights: ['No rent control statewide', 'Flexible lease terms'], localCourts: [{ name: 'Alaska Court System', url: 'https://courts.alaska.gov' }], evictionFilingFee: '$150', winterEvictionBan: false },
  { code: 'AZ', name: 'Arizona', landlordScore: 9, evictionNoticeDays: 5, evictionTotalDays: 21, securityDepositMax: '1.5 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 2, requiredDisclosures: ['Lead paint', 'Pool barriers', 'Bed bug history'], keyTenantRights: ['Habitability', 'Security deposit return in 14 days'], keyLandlordRights: ['Fastest eviction in US', 'Preempts local rent control', 'Strict tenant obligations'], localCourts: [{ name: 'AZ Justice Courts', url: 'https://www.azcourts.gov/selfservicecenter' }], evictionFilingFee: '$35–$220', winterEvictionBan: false },
  { code: 'AR', name: 'Arkansas', landlordScore: 9, evictionNoticeDays: 3, evictionTotalDays: 21, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint (pre-1978)'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No habitability statute (common law only)', 'No entry notice required', 'Criminal unlawful detainer option'], localCourts: [{ name: 'AR District Courts', url: 'https://arcourts.gov' }], evictionFilingFee: '$65–$165', winterEvictionBan: false },
  { code: 'CA', name: 'California', landlordScore: 1, evictionNoticeDays: 3, evictionTotalDays: 90, securityDepositMax: '1 month (as of 2024)', rentControl: true, rentControlCities: ['Los Angeles', 'San Francisco', 'Oakland', 'San Jose', 'Santa Monica', 'Berkeley'], lateFeeCap: '5–10% (varies)', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Mold', 'Pest history', 'Flood zone', 'Death on property (3yrs)'], keyTenantRights: ['AB 1482 just cause eviction', 'Rent increase caps (5%+CPI)', 'Relocation assistance'], keyLandlordRights: ['Can recover possession eventually', 'Can charge application fees'], localCourts: [{ name: 'CA Courts Self-Help', url: 'https://selfhelp.courts.ca.gov' }], evictionFilingFee: '$240–$450', winterEvictionBan: false },
  { code: 'CO', name: 'Colorado', landlordScore: 4, evictionNoticeDays: 10, evictionTotalDays: 60, securityDepositMax: 'None (return in 30 days)', rentControl: false, rentControlCities: [], lateFeeCap: '$50 or 5%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Mold disclosure', 'Radon'], keyTenantRights: ['Repair & deduct', 'Retaliation protections', 'Domestic violence protections'], keyLandlordRights: ['No rent control statewide', 'Month-to-month: 21 day notice'], localCourts: [{ name: 'CO Judicial Branch', url: 'https://www.courts.state.co.us' }], evictionFilingFee: '$85–$224', winterEvictionBan: false },
  { code: 'CT', name: 'Connecticut', landlordScore: 3, evictionNoticeDays: 3, evictionTotalDays: 75, securityDepositMax: '2 months (1 month if 62+)', rentControl: false, rentControlCities: [], lateFeeCap: '5% after 9-day grace', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Radon', 'Flood zone'], keyTenantRights: ['Right to cure', 'Repair & deduct', 'Summary process protections'], keyLandlordRights: ['No statewide rent control'], localCourts: [{ name: 'CT Judicial', url: 'https://jud.ct.gov' }], evictionFilingFee: '$175', winterEvictionBan: false },
  { code: 'DE', name: 'Delaware', landlordScore: 5, evictionNoticeDays: 5, evictionTotalDays: 60, securityDepositMax: '1 month (after 1yr)', rentControl: false, rentControlCities: [], lateFeeCap: '5%', entryNoticeHours: 12, requiredDisclosures: ['Lead paint', 'Condition of premises'], keyTenantRights: ['Habitability', '12-hr entry notice'], keyLandlordRights: ['No rent control', 'Can require renters insurance'], localCourts: [{ name: 'DE Justice of the Peace', url: 'https://courts.delaware.gov/JoP' }], evictionFilingFee: '$40–$90', winterEvictionBan: false },
  { code: 'FL', name: 'Florida', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 12, requiredDisclosures: ['Lead paint', 'Radon', 'Sinkholes'], keyTenantRights: ['7-day cure for non-monetary breach', 'Deposit return in 15–60 days'], keyLandlordRights: ['Fast eviction', 'No deposit cap', 'Preempts local rent control'], localCourts: [{ name: 'FL Courts', url: 'https://www.flcourts.gov' }], evictionFilingFee: '$185–$400', winterEvictionBan: false },
  { code: 'GA', name: 'Georgia', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Landlord identity'], keyTenantRights: ['Basic habitability', 'Security deposit itemization'], keyLandlordRights: ['No deposit cap', 'No entry notice required', 'Fast dispossessory process'], localCourts: [{ name: 'GA Magistrate Courts', url: 'https://georgiacourts.gov/courts/magistrate-court' }], evictionFilingFee: '$60–$120', winterEvictionBan: false },
  { code: 'HI', name: 'Hawaii', landlordScore: 3, evictionNoticeDays: 5, evictionTotalDays: 60, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Mold'], keyTenantRights: ['Strong habitability code', '24-hr entry notice strictly enforced'], keyLandlordRights: ['Can evict for lease violations', 'No rent control statewide'], localCourts: [{ name: 'HI District Courts', url: 'https://www.courts.state.hi.us' }], evictionFilingFee: '$110–$215', winterEvictionBan: false },
  { code: 'ID', name: 'Idaho', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 25, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability', '24-hr entry notice'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Fast eviction'], localCourts: [{ name: 'ID Courts', url: 'https://isc.idaho.gov' }], evictionFilingFee: '$66–$166', winterEvictionBan: false },
  { code: 'IL', name: 'Illinois', landlordScore: 4, evictionNoticeDays: 5, evictionTotalDays: 60, securityDepositMax: 'None (Chicago varies)', rentControl: false, rentControlCities: ['Chicago (local ordinances)'], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Carbon monoxide', 'Bed bugs (Chicago)'], keyTenantRights: ['Chicago RLTO protections', 'Repair & deduct', 'Retaliatory eviction defense'], keyLandlordRights: ['No statewide rent control', 'Can recover attorney fees'], localCourts: [{ name: 'IL Courts', url: 'https://www.illinoiscourts.gov' }], evictionFilingFee: '$240–$350', winterEvictionBan: false },
  { code: 'IN', name: 'Indiana', landlordScore: 8, evictionNoticeDays: 10, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Move-in inspection'], keyTenantRights: ['Habitability', 'Security deposit return in 45 days'], keyLandlordRights: ['No deposit cap', 'No entry notice required', 'No rent control'], localCourts: [{ name: 'IN Courts', url: 'https://www.in.gov/courts' }], evictionFilingFee: '$86–$120', winterEvictionBan: false },
  { code: 'IA', name: 'Iowa', landlordScore: 6, evictionNoticeDays: 3, evictionTotalDays: 35, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', '3-day pay or vacate cure period'], keyLandlordRights: ['No rent control', 'Fast filing process'], localCourts: [{ name: 'IA Courts', url: 'https://www.iowacourts.gov' }], evictionFilingFee: '$95', winterEvictionBan: false },
  { code: 'KS', name: 'Kansas', landlordScore: 7, evictionNoticeDays: 3, evictionTotalDays: 28, securityDepositMax: '1 month (unfurnished)', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitable premises', '24-hr notice for repairs'], keyLandlordRights: ['Fast eviction', 'No rent control', 'Can charge re-renting fee'], localCourts: [{ name: 'KS Courts', url: 'https://www.kscourts.org' }], evictionFilingFee: '$88–$168', winterEvictionBan: false },
  { code: 'KY', name: 'Kentucky', landlordScore: 7, evictionNoticeDays: 7, evictionTotalDays: 35, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', 'Security deposit return in 30 days'], keyLandlordRights: ['No deposit cap', 'No rent control'], localCourts: [{ name: 'KY Courts', url: 'https://kycourts.gov' }], evictionFilingFee: '$60–$105', winterEvictionBan: false },
  { code: 'LA', name: 'Louisiana', landlordScore: 8, evictionNoticeDays: 5, evictionTotalDays: 25, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Implied warranty of habitability'], keyLandlordRights: ['No entry notice required', 'Fast rule for possession', 'No rent control'], localCourts: [{ name: 'LA Parish Courts', url: 'https://www.lasc.org' }], evictionFilingFee: '$100–$250', winterEvictionBan: false },
  { code: 'ME', name: 'Maine', landlordScore: 4, evictionNoticeDays: 7, evictionTotalDays: 50, securityDepositMax: '2 months', rentControl: false, rentControlCities: ['Portland'], lateFeeCap: '4% after 15-day grace', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Bedbug history', 'Energy efficiency'], keyTenantRights: ['45-day notice to quit', 'Repair & deduct', 'Retaliation protections'], keyLandlordRights: ['Can charge late fees', 'No statewide rent control'], localCourts: [{ name: 'ME Courts', url: 'https://www.courts.maine.gov' }], evictionFilingFee: '$80–$100', winterEvictionBan: true },
  { code: 'MD', name: 'Maryland', landlordScore: 4, evictionNoticeDays: 4, evictionTotalDays: 60, securityDepositMax: '2 months', rentControl: false, rentControlCities: ['Takoma Park'], lateFeeCap: '5%', entryNoticeHours: 0, requiredDisclosures: ['Lead paint (strict)', 'Mold', 'Flood', 'Utilities'], keyTenantRights: ['Right to jury trial in eviction', 'Escrow rights'], keyLandlordRights: ['Can recover court costs'], localCourts: [{ name: 'MD Courts', url: 'https://www.courts.state.md.us' }], evictionFilingFee: '$35–$51', winterEvictionBan: false },
  { code: 'MA', name: 'Massachusetts', landlordScore: 2, evictionNoticeDays: 14, evictionTotalDays: 90, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None (30-day grace)', entryNoticeHours: 24, requiredDisclosures: ['Lead paint (detailed)', 'Statement of condition', 'Utility info'], keyTenantRights: ['14-day notice for non-payment', 'Right to jury trial', '30-day cure period'], keyLandlordRights: ['Can recover holdover damages'], localCourts: [{ name: 'MA Housing Court', url: 'https://www.mass.gov/housing-court' }], evictionFilingFee: '$180–$240', winterEvictionBan: false },
  { code: 'MI', name: 'Michigan', landlordScore: 6, evictionNoticeDays: 7, evictionTotalDays: 45, securityDepositMax: '1.5 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Truth in Renting Act'], keyTenantRights: ['Habitability', 'Rent escrow option', '24-hr entry notice'], keyLandlordRights: ['No rent control', 'Summary proceedings available'], localCourts: [{ name: 'MI Courts', url: 'https://www.courts.michigan.gov' }], evictionFilingFee: '$45–$150', winterEvictionBan: false },
  { code: 'MN', name: 'Minnesota', landlordScore: 3, evictionNoticeDays: 14, evictionTotalDays: 60, securityDepositMax: 'None', rentControl: false, rentControlCities: ['St. Paul (2022 referendum)'], lateFeeCap: '8% after 5-day grace', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Radon', 'Energy efficiency'], keyTenantRights: ['Rent escrow', 'Rent withholding', 'Tenant remedies action'], keyLandlordRights: ['Can recover attorney fees'], localCourts: [{ name: 'MN Courts', url: 'https://www.mncourts.gov' }], evictionFilingFee: '$285', winterEvictionBan: false },
  { code: 'MS', name: 'Mississippi', landlordScore: 9, evictionNoticeDays: 3, evictionTotalDays: 20, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No deposit cap', 'No entry notice required', 'No rent control', 'Fastest eviction timeline'], localCourts: [{ name: 'MS Justice Courts', url: 'https://courts.ms.gov' }], evictionFilingFee: '$60–$140', winterEvictionBan: false },
  { code: 'MO', name: 'Missouri', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 25, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No rent control', 'No entry notice required', 'Fast unlawful detainer'], localCourts: [{ name: 'MO Courts', url: 'https://www.courts.mo.gov' }], evictionFilingFee: '$50–$100', winterEvictionBan: false },
  { code: 'MT', name: 'Montana', landlordScore: 6, evictionNoticeDays: 3, evictionTotalDays: 40, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Move-in checklist required'], keyTenantRights: ['Habitable conditions', '24-hr entry notice'], keyLandlordRights: ['No deposit cap', 'No rent control'], localCourts: [{ name: 'MT Courts', url: 'https://courts.mt.gov' }], evictionFilingFee: '$30–$100', winterEvictionBan: false },
  { code: 'NE', name: 'Nebraska', landlordScore: 7, evictionNoticeDays: 7, evictionTotalDays: 30, securityDepositMax: '1.25 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Landlord identity'], keyTenantRights: ['Habitability', 'Repair & deduct'], keyLandlordRights: ['Fast filing', 'No rent control'], localCourts: [{ name: 'NE Courts', url: 'https://supremecourt.nebraska.gov' }], evictionFilingFee: '$45–$76', winterEvictionBan: false },
  { code: 'NV', name: 'Nevada', landlordScore: 7, evictionNoticeDays: 7, evictionTotalDays: 35, securityDepositMax: '3 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Shared utilities', 'Bedbug disclosure'], keyTenantRights: ['Habitability', 'Retaliation protection'], keyLandlordRights: ['Expedited eviction for lease violations', 'No rent control statewide'], localCourts: [{ name: 'NV Courts', url: 'https://nvcourts.gov' }], evictionFilingFee: '$71–$270', winterEvictionBan: false },
  { code: 'NH', name: 'New Hampshire', landlordScore: 6, evictionNoticeDays: 7, evictionTotalDays: 45, securityDepositMax: '1 month or $100', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Sprinkler systems'], keyTenantRights: ['Habitability', 'Deposit return in 30 days'], keyLandlordRights: ['No rent control', 'Low filing fees'], localCourts: [{ name: 'NH Circuit Courts', url: 'https://www.courts.nh.gov' }], evictionFilingFee: '$90–$155', winterEvictionBan: false },
  { code: 'NJ', name: 'New Jersey', landlordScore: 2, evictionNoticeDays: 30, evictionTotalDays: 90, securityDepositMax: '1.5 months', rentControl: true, rentControlCities: ['Newark', 'Jersey City', 'Hoboken', 'Trenton', 'Camden'], lateFeeCap: '5% (common)', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Truth in Renting Guide', 'Flood zone', 'Radon'], keyTenantRights: ['Anti-Eviction Act (just cause required)', 'Rent leveling', 'Right to counsel (some cities)'], keyLandlordRights: ['Can recover past-due rent', 'Can terminate for good cause'], localCourts: [{ name: 'NJ Special Civil Part', url: 'https://www.njcourts.gov/courts/civil/landlord.html' }], evictionFilingFee: '$50–$250', winterEvictionBan: false },
  { code: 'NM', name: 'New Mexico', landlordScore: 4, evictionNoticeDays: 3, evictionTotalDays: 55, securityDepositMax: '1 month (under $500/mo)', rentControl: false, rentControlCities: [], lateFeeCap: '10%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Furnishings list'], keyTenantRights: ['Repair & deduct', 'Habitability', 'Retaliation defense'], keyLandlordRights: ['Can charge 10% late fee', 'No statewide rent control'], localCourts: [{ name: 'NM Courts', url: 'https://nmcourts.gov' }], evictionFilingFee: '$50–$100', winterEvictionBan: false },
  { code: 'NY', name: 'New York', landlordScore: 1, evictionNoticeDays: 14, evictionTotalDays: 120, securityDepositMax: '1 month', rentControl: true, rentControlCities: ['New York City', 'Albany', 'Yonkers', 'Kingston', 'Newburgh'], lateFeeCap: '5% after 5-day grace (NYC)', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Bedbug history', 'Mold', 'Flood zone', 'Notice of rights'], keyTenantRights: ['HSTPA 2019 protections', 'Good cause eviction (NYC)', 'Right to counsel (NYC)', 'SCRIE/DRIE freeze programs'], keyLandlordRights: ['Can recover 3x for willful overcharge claims'], localCourts: [{ name: 'NY Housing Courts', url: 'https://nycourts.gov/courts/nyc/housing' }], evictionFilingFee: '$45–$210', winterEvictionBan: false },
  { code: 'NC', name: 'North Carolina', landlordScore: 8, evictionNoticeDays: 10, evictionTotalDays: 30, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: '5% or $15', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Move-in checklist'], keyTenantRights: ['Habitability', 'Deposit return in 30 days'], keyLandlordRights: ['No rent control (preempted)', 'Fast summary ejectment'], localCourts: [{ name: 'NC Small Claims', url: 'https://www.nccourts.gov' }], evictionFilingFee: '$96', winterEvictionBan: false },
  { code: 'ND', name: 'North Dakota', landlordScore: 7, evictionNoticeDays: 3, evictionTotalDays: 30, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', '24-hr entry notice'], keyLandlordRights: ['No rent control', 'Fast eviction filing'], localCourts: [{ name: 'ND Courts', url: 'https://www.ndcourts.gov' }], evictionFilingFee: '$80', winterEvictionBan: false },
  { code: 'OH', name: 'Ohio', landlordScore: 7, evictionNoticeDays: 3, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', '24-hr entry notice', 'Repair & deduct'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Expedited forcible entry'], localCourts: [{ name: 'OH Municipal Courts', url: 'https://www.supremecourt.ohio.gov' }], evictionFilingFee: '$100–$130', winterEvictionBan: false },
  { code: 'OK', name: 'Oklahoma', landlordScore: 8, evictionNoticeDays: 5, evictionTotalDays: 25, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', 'Deposit return in 30–45 days'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Fast FED process'], localCourts: [{ name: 'OK District Courts', url: 'https://www.oscn.net' }], evictionFilingFee: '$67–$164', winterEvictionBan: false },
  { code: 'OR', name: 'Oregon', landlordScore: 2, evictionNoticeDays: 10, evictionTotalDays: 75, securityDepositMax: 'None (return in 31 days)', rentControl: true, rentControlCities: ['Portland', 'Eugene', 'Bend (statewide 7%+CPI cap)'], lateFeeCap: '$50 or 5%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Mold', 'Drug manufacturing history', 'Carbon monoxide'], keyTenantRights: ['Statewide rent control (SB 608)', 'Just cause eviction statewide', 'Relocation assistance'], keyLandlordRights: ['Can terminate for substantial violation'], localCourts: [{ name: 'OR Courts', url: 'https://www.courts.oregon.gov' }], evictionFilingFee: '$88', winterEvictionBan: false },
  { code: 'PA', name: 'Pennsylvania', landlordScore: 5, evictionNoticeDays: 10, evictionTotalDays: 60, securityDepositMax: '2 months (1st yr), 1 month (after)', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Bed bugs (Philadelphia)'], keyTenantRights: ['Habitability', 'Deposit return in 30 days'], keyLandlordRights: ['No rent control', 'Distress for rent available'], localCourts: [{ name: 'PA Magisterial District Courts', url: 'https://www.pacourts.us' }], evictionFilingFee: '$96–$250', winterEvictionBan: false },
  { code: 'RI', name: 'Rhode Island', landlordScore: 3, evictionNoticeDays: 5, evictionTotalDays: 65, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint (strict)', 'Landlord identity', 'Statement of condition'], keyTenantRights: ['Repair & deduct', 'Lead inspection rights', 'Retaliation defense'], keyLandlordRights: ['Can evict holdover tenants', 'No rent control'], localCourts: [{ name: 'RI District Courts', url: 'https://www.courts.ri.gov' }], evictionFilingFee: '$80–$120', winterEvictionBan: false },
  { code: 'SC', name: 'South Carolina', landlordScore: 8, evictionNoticeDays: 5, evictionTotalDays: 28, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', '24-hr notice for routine entry'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Fast rules to vacate'], localCourts: [{ name: 'SC Magistrate Courts', url: 'https://www.sccourts.org' }], evictionFilingFee: '$80–$150', winterEvictionBan: false },
  { code: 'SD', name: 'South Dakota', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 25, securityDepositMax: '1 month', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No rent control', 'No entry notice required', 'Fast eviction'], localCourts: [{ name: 'SD Magistrate Courts', url: 'https://ujs.sd.gov' }], evictionFilingFee: '$70', winterEvictionBan: false },
  { code: 'TN', name: 'Tennessee', landlordScore: 8, evictionNoticeDays: 14, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: '10%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', '14-day cure period'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Landlord-favorable URLTA provisions'], localCourts: [{ name: 'TN General Sessions Courts', url: 'https://www.tncourts.gov' }], evictionFilingFee: '$80–$180', winterEvictionBan: false },
  { code: 'TX', name: 'Texas', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 21, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: '12% (4+ units), 10% (fewer)', entryNoticeHours: 0, requiredDisclosures: ['Lead paint', 'Landlord identity', 'Back fees notice'], keyTenantRights: ['Repair & deduct', 'Habitability'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Expedited eviction (Rule 510)', 'Landlord lien on property'], localCourts: [{ name: 'TX Justice of Peace Courts', url: 'https://www.txcourts.gov' }], evictionFilingFee: '$46–$100', winterEvictionBan: false },
  { code: 'UT', name: 'Utah', landlordScore: 7, evictionNoticeDays: 3, evictionTotalDays: 30, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Habitability', 'Deposit return in 30 days'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Fast unlawful detainer'], localCourts: [{ name: 'UT Courts', url: 'https://www.utcourts.gov' }], evictionFilingFee: '$75–$185', winterEvictionBan: false },
  { code: 'VT', name: 'Vermont', landlordScore: 3, evictionNoticeDays: 14, evictionTotalDays: 70, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 48, requiredDisclosures: ['Lead paint', 'Rental housing code', 'Efficiency Vermont'], keyTenantRights: ['48-hr entry notice', '30-day cure period', 'Retaliation defense'], keyLandlordRights: ['No rent control', 'Can evict for nonpayment'], localCourts: [{ name: 'VT Superior Courts', url: 'https://www.vermontjudiciary.org' }], evictionFilingFee: '$155', winterEvictionBan: false },
  { code: 'VA', name: 'Virginia', landlordScore: 5, evictionNoticeDays: 5, evictionTotalDays: 55, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: '10%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Move-in inspection', 'Mold (visible)'], keyTenantRights: ['Habitability', 'Repair & deduct', 'Right to cure (VRLTA)'], keyLandlordRights: ['No rent control', 'Can require renters insurance'], localCourts: [{ name: 'VA General District Courts', url: 'https://www.vacourts.gov' }], evictionFilingFee: '$25–$75', winterEvictionBan: false },
  { code: 'WA', name: 'Washington', landlordScore: 2, evictionNoticeDays: 14, evictionTotalDays: 90, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'Mold', 'Carbon monoxide', 'Fire safety', 'Move-in checklist'], keyTenantRights: ['Just cause eviction statewide (RLTA 2021)', 'Right to counsel (Seattle)', 'Relocation assistance'], keyLandlordRights: ['Can apply for immediate writ with $5k bond'], localCourts: [{ name: 'WA Courts', url: 'https://www.courts.wa.gov' }], evictionFilingFee: '$85–$240', winterEvictionBan: false },
  { code: 'WV', name: 'West Virginia', landlordScore: 7, evictionNoticeDays: 5, evictionTotalDays: 30, securityDepositMax: '2 months', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No rent control', 'No entry notice required', 'Fast eviction process'], localCourts: [{ name: 'WV Magistrate Courts', url: 'https://www.courtswv.gov' }], evictionFilingFee: '$60–$80', winterEvictionBan: false },
  { code: 'WI', name: 'Wisconsin', landlordScore: 7, evictionNoticeDays: 5, evictionTotalDays: 40, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 12, requiredDisclosures: ['Lead paint', 'Landlord identity', 'Nonstandard rental provisions'], keyTenantRights: ['Habitability', '12-hr entry notice', 'Repair & deduct'], keyLandlordRights: ['No deposit cap', 'No rent control', 'Landlord-favorable ATCP 134'], localCourts: [{ name: 'WI Circuit Courts', url: 'https://www.wicourts.gov' }], evictionFilingFee: '$94.50', winterEvictionBan: false },
  { code: 'WY', name: 'Wyoming', landlordScore: 8, evictionNoticeDays: 3, evictionTotalDays: 25, securityDepositMax: 'None', rentControl: false, rentControlCities: [], lateFeeCap: 'None', entryNoticeHours: 0, requiredDisclosures: ['Lead paint'], keyTenantRights: ['Basic habitability'], keyLandlordRights: ['No deposit cap', 'No rent control', 'No entry notice required', 'Fast eviction'], localCourts: [{ name: 'WY Circuit Courts', url: 'https://www.courts.state.wy.us' }], evictionFilingFee: '$40–$80', winterEvictionBan: false },
  { code: 'DC', name: 'Washington D.C.', landlordScore: 1, evictionNoticeDays: 30, evictionTotalDays: 120, securityDepositMax: '1 month', rentControl: true, rentControlCities: ['All of DC'], lateFeeCap: '5%', entryNoticeHours: 24, requiredDisclosures: ['Lead paint', 'TOPA rights', 'Notice of rent charged', 'Housing code compliance'], keyTenantRights: ['TOPA (right to purchase)', 'Rent control most buildings', 'Just cause required', 'Right to counsel'], keyLandlordRights: ['Can petition for hardship increases', 'Capital improvement petitions'], localCourts: [{ name: 'DC Landlord Tenant Court', url: 'https://www.dccourts.gov/superior-court/landlord-tenant-branch' }], evictionFilingFee: '$15', winterEvictionBan: false },
];

export const getStateByCode = (code: string) => STATE_LAWS.find(s => s.code === code);
export const getLandlordFriendlyStates = () => STATE_LAWS.filter(s => s.landlordScore >= 7).sort((a,b) => b.landlordScore - a.landlordScore);
export const getRentControlStates = () => STATE_LAWS.filter(s => s.rentControl);
